/**
 * Offline expense-advice scenarios (regex catalog) extracted from
 * `utils/aiService.ts` for maintainability. Pure data + lookup; no
 * runtime side effects, no network calls, no logic changes from
 * the original inline implementation.
 */

export type ExpenseScenario = {
  id: string;
  category:
    | "food"
    | "transport"
    | "utilities"
    | "education"
    | "health"
    | "shopping"
    | "entertainment"
    | "family"
    | "work"
    | "housing"
    | "savings";
  re: RegExp;
  typicalMin: number;
  typicalMax: number;
  analysis: string;
  localTip: string;
  cheaperOption: string;
};

export const OFFLINE_EXPENSE_SCENARIOS: ExpenseScenario[] = [
  // Food
  { id: "food-canteen", category: "food", re: /(university canteen|canteen lunch|campus lunch)/i, typicalMin: 2000, typicalMax: 9000, analysis: "Campus canteen line item choti lagti hai, lekin daily snacks + extra juice mila ke month end pe leak ban jati hai — classic student tax.", localTip: "Mon–Sat ke liye weekly meal cap lock karo; chai/snacks alternate days pe shift karo — discipline boring hai lekin kaam karti hai.", cheaperOption: "Hostel ke liye Imtiaz/Metro/Naheed se monthly bulk snack run — roughly PKR 1,500–4,000 tak realistic relief milta hai." },
  { id: "food-dhaba", category: "food", re: /(dhaba|hotel food|tea stall|outside food)/i, typicalMin: 3000, typicalMax: 15000, analysis: "Dhaba spend 'chota kharcha' feel deta hai, frequency high ho toh yeh silent killer ban jata hai — wallet ko pata hota hai, tumhe late pata chalta hai.", localTip: "2–3 fixed dhaba days rakho; baaki lunch box / ghar ka dabba — simple rule, big impact.", cheaperOption: "Ghar prep + local kiryana bulk — monthly PKR 3k–8k range mein squeeze possible hai agar pattern change ho." },
  { id: "food-restaurant", category: "food", re: /(restaurant|fine dining|dinner out|buffet)/i, typicalMin: 4000, typicalMax: 30000, analysis: "Restaurant occasional = vibe; weekly habit = budget pe pressure — service charge + parking + tips alag tax lag jata hai.", localTip: "Family outings month mein 1–2 events cap — 'every weekend fine dining' middle class ko quietly finish kar deta hai.", cheaperOption: "Foodpanda pickup + bank card discounts + iftar bundles — PKR 1k–6k band realistic hai agar deals smart use ho." },
  { id: "food-grocery", category: "food", re: /(grocery|kiryana|ration|home grocery)/i, typicalMin: 12000, typicalMax: 70000, analysis: "Grocery need hai, lekin list ke baghair repeat trips = impulse + fuel + time sab leak — yeh boring mistake expensive padti hai.", localTip: "Monthly ration list + weekly sabzi list same page pe — 'andar aya, sab kuch le aya' wala mode band karo.", cheaperOption: "Metro/Imtiaz/utility store mix + Sunday bazaar for fresh — PKR 3k–12k monthly band common hai jab unit-price compare hota hai." },
  { id: "food-qasai", category: "food", re: /(qasai|butcher|meat|mutton|beef|chicken)/i, typicalMin: 5000, typicalMax: 30000, analysis: "Meat bucket inflation ke saath rocket mode mein chala jata hai — quantity + premium cuts = bill shock.", localTip: "Monthly meat map + freezer portions — 'aaj mood hai' wala daily qasai trip mehnga game hai.", cheaperOption: "Wholesale cut + combo pieces — PKR 2k–6k monthly squeeze realistic hai jab bulk planning ho." },
  { id: "food-sabzi", category: "food", re: /(sabzi mandi|sabzi|vegetable|fruit mandi|fruit)/i, typicalMin: 3000, typicalMax: 15000, analysis: "Sabzi/fruit planning se sasta rehta hai; har roz cart se random pick = premium per kg + waste bhi.", localTip: "Week mein 2 mandi trips + seasonal fruit priority — local + fresh dono win.", cheaperOption: "Mandi vs cart rate compare — PKR 1k–3k monthly band easy hai agar bulk buy ho." },
  { id: "food-atta", category: "food", re: /(atta chakki|atta|flour|chakki)/i, typicalMin: 2500, typicalMax: 12000, analysis: "Atta base expense hai; emergency chakki premium + time waste dono lagte hain.", localTip: "Usage track karke refill calendar banao — last-minute 5kg bags mehngay padte hain.", cheaperOption: "Chakki rate compare + 15–30 day stock — PKR 500–2k save zone realistic hai." },
  { id: "food-dairy", category: "food", re: /(doodh|milk|dairy|dahi|yogurt|lassi)/i, typicalMin: 3000, typicalMax: 18000, analysis: "Dairy daily recurring hai — extra doodh, extra dahi, extra lassi quietly bill inflate karti hai.", localTip: "Per-day liter cap + chai doodh alag track — boring hai lekin month end calm deta hai.", cheaperOption: "Local dairy contract ya tetra promos — PKR 700–2.5k band common hai." },
  { id: "food-mithai", category: "food", re: /(mithai|sweets|bakery sweets|halwa)/i, typicalMin: 1500, typicalMax: 12000, analysis: "Mithai mostly event spend; random gifting start ho toh overshoot emotional + financial dono.", localTip: "Sirf occasions pe sweet budget — 'just because' box avoid.", cheaperOption: "Known shop off-peak pre-order — PKR 500–2k save realistic." },
  { id: "food-fastfood", category: "food", re: /(fast food|burger|pizza|kfc|mcdonald|broast)/i, typicalMin: 2500, typicalMax: 25000, analysis: "Fast food = convenience tax; delivery + small order fee mila ke pain double.", localTip: "Weekday zero fast food rule + weekend treat — dopamine same, leak kam.", cheaperOption: "Pickup deals + ghar ka simple swap — PKR 2k–7k monthly band possible." },
  { id: "food-wedding-catering", category: "food", re: /(wedding catering|walima food|shaadi khana|catering)/i, typicalMin: 80000, typicalMax: 800000, analysis: "Shaadi catering = one-time heavy hit; social pressure menu ko balloon kar deta hai.", localTip: "Pehle guest count lock, phir menu — reverse order mein budget explode hota hai.", cheaperOption: "Per-head negotiate + weekday slot — PKR 20k–200k range mein relief cases mein milta hai." },
  { id: "food-iftar", category: "food", re: /(iftar deal|ramzan deal|sehri)/i, typicalMin: 2500, typicalMax: 30000, analysis: "Ramzan deals 'cheap' lagti hain, frequency high ho toh total bhi high — classic trap.", localTip: "Ghar base iftar + bahar max weekly 1 — balance realistic rehta hai.", cheaperOption: "Community bulk + grocery bundle — PKR 2k–8k squeeze possible." },
  // Transport
  { id: "transport-rickshaw", category: "transport", re: /(rickshaw daily|riksha daily|daily rickshaw)/i, typicalMin: 4000, typicalMax: 22000, analysis: "Daily riksha predictable hai, lekin poora month stack ho toh transport bucket top 3 mein aa jata hai — especially office commute.", localTip: "Fixed route + known driver monthly deal try karo; peak hours pe rate drama kam hota hai.", cheaperOption: "Bus/chingchi mix same route pe — PKR 2k–7k monthly squeeze realistic hai." },
  { id: "transport-chingchi", category: "transport", re: /(chingchi|qingqi|chinchy)/i, typicalMin: 2000, typicalMax: 9000, analysis: "Chingchi cheap vibe deti hai, lekin safety + time tradeoff hota hai — frequency high ho toh total bhi add up.", localTip: "Peak hour alternate route map karo — panic pick = double fare sometimes.", cheaperOption: "Monthly shared pass style deal agar same stand se — PKR 500–1.5k band possible." },
  { id: "transport-bus", category: "transport", re: /(local bus|wagon fare|bus fare)/i, typicalMin: 1500, typicalMax: 7000, analysis: "Local bus generally efficient; multiple hops + rush transfers = hidden time + money tax.", localTip: "Single-line commute optimize — 'har stop change' mode avoid.", cheaperOption: "Card/pass where available — PKR 300–1k monthly realistic." },
  { id: "transport-uber-careem", category: "transport", re: /(uber|careem|indrive)/i, typicalMin: 5000, typicalMax: 45000, analysis: "Ride-hailing comfort deta hai; habit ban jaye toh yeh discretionary se 'necessary' ban jata hai — leak fast.", localTip: "Peak avoid + pool where safe; short trips pe riksha compare zaroori.", cheaperOption: "InDrive vs Careem per trip compare — PKR 2k–10k monthly band common hai." },
  { id: "transport-bike-petrol", category: "transport", re: /(petrol bike|bike petrol|motorcycle fuel)/i, typicalMin: 3500, typicalMax: 16000, analysis: "Bike fuel mid-range hota hai; choti choti trips = burn rate up — pump wala tumhara fan ban jata hai.", localTip: "Trip batch + tyre pressure monthly — boring maintenance = fuel save.", cheaperOption: "Discount days + tune-up discipline — PKR 700–2.5k squeeze realistic." },
  { id: "transport-car-petrol", category: "transport", re: /(petrol car|car fuel|car petrol)/i, typicalMin: 12000, typicalMax: 90000, analysis: "Car fuel often biggest line item — traffic + AC idle = silent money fire.", localTip: "Weekly errands batch + unnecessary idle kam — AC guilt real hai.", cheaperOption: "Carpool + planned routes — PKR 4k–20k monthly relief cases mein." },
  { id: "transport-cng", category: "transport", re: /\bcng\b/i, typicalMin: 4000, typicalMax: 20000, analysis: "CNG cost-effective ho sakta hai; line + availability = time cost bhi add karo mentally.", localTip: "Refill non-peak — line shorter, mood better.", cheaperOption: "Hybrid route planning — PKR 1k–4k monthly band possible." },
  { id: "transport-school-van", category: "transport", re: /(school van|school pickup|school transport)/i, typicalMin: 3000, typicalMax: 18000, analysis: "School van fixed family cost; annual increment silent creep karti hai.", localTip: "Sibling routes consolidate — operator se polite negotiation.", cheaperOption: "Nearby families shared van — PKR 1k–3k realistic." },
  { id: "transport-intercity-bus", category: "transport", re: /(intercity bus|daewoo|faisal movers|bus ticket)/i, typicalMin: 2000, typicalMax: 20000, analysis: "Intercity occasional = fine; frequent = travel bucket explode.", localTip: "Advance booking + off-peak slots — simple hack.", cheaperOption: "Early bird discounts — PKR 300–2k per trip band." },
  { id: "transport-train", category: "transport", re: /(train ticket|railway ticket)/i, typicalMin: 1000, typicalMax: 15000, analysis: "Train often value king intercity ke liye — time tradeoff accept karo toh wallet happy.", localTip: "Return ticket plan saath — last-minute premium avoid.", cheaperOption: "Class selection optimize — PKR 500–2.5k per journey realistic." },
  // Utilities
  { id: "utilities-wapda-low", category: "utilities", re: /(wapda|bijli bill|electricity bill).*(low|kam)/i, typicalMin: 2000, typicalMax: 7000, analysis: "Low bijli bill healthy zone — maintain karna game hai, celebrate mat karo aur usage loose mat karo.", localTip: "Standby load + purane bulbs = silent units — yahan se creep start hoti hai.", cheaperOption: "Full LED shift — PKR 300–1k monthly band common." },
  { id: "utilities-wapda-medium", category: "utilities", re: /(wapda|bijli bill|electricity bill).*(medium|avg|average)/i, typicalMin: 7000, typicalMax: 18000, analysis: "Medium bill manageable; summer spike agar ignore karo toh 'acha tha' se 'kya hogaya' fast travel.", localTip: "Peak hours pe heavy appliances stagger — AC + iron + geyser same time = villain combo.", cheaperOption: "Tariff timing aware usage — PKR 1k–3.5k squeeze possible." },
  { id: "utilities-wapda-high", category: "utilities", re: /(wapda|bijli bill|electricity bill|k electric|lesco|iesco|fesco|pesco)/i, typicalMin: 18000, typicalMax: 90000, analysis: "High bill = cooling load + inefficient appliances + bad habits — mix hota hai, blame single factor mat karo.", localTip: "AC 26°C + insulation + schedule — old school but gold.", cheaperOption: "Inverter appliances post payback — PKR 3k–12k monthly relief realistic in many homes." },
  { id: "utilities-gas", category: "utilities", re: /(sngpl|sui gas|gas bill)/i, typicalMin: 1500, typicalMax: 20000, analysis: "Gas bill seasonal; winter planning miss = shock + geyser drama.", localTip: "Geyser time blocks — random 'on all day' mode expensive.", cheaperOption: "Leak check + efficient usage — PKR 500–2.5k monthly band." },
  { id: "utilities-ups-battery", category: "utilities", re: /(ups battery|inverter battery|battery replacement)/i, typicalMin: 18000, typicalMax: 85000, analysis: "Battery one-time heavy hit — emergency fund se hi sane lagta hai.", localTip: "Water/maintenance schedule miss = early death = repeat pain.", cheaperOption: "2–3 dealer quotes + warranty read — PKR 2k–10k save cases mein." },
  { id: "utilities-generator-fuel", category: "utilities", re: /(generator fuel|genset|generator petrol|generator diesel)/i, typicalMin: 3000, typicalMax: 40000, analysis: "Load-shedding months mein generator fuel rocket — poora ghar backup = poora wallet backup nahi hota.", localTip: "Runtime cap + fan-first policy — selective rooms adult decision hai.", cheaperOption: "Selective backup strategy — PKR 1.5k–6k monthly squeeze realistic." },
  { id: "utilities-loadshedding", category: "utilities", re: /(load shedding|loadshed|backup power)/i, typicalMin: 2000, typicalMax: 30000, analysis: "Backup hidden costs ignore ho jate hain — battery, fuel, maintenance teeno stack.", localTip: "Backup ko alag budget line item — merge mat karo bijli ke saath blind.", cheaperOption: "Low-watt backup design — PKR 1k–4k recurring kam ho sakta hai." },
  { id: "utilities-water-tanker", category: "utilities", re: /(water tanker|tanker water)/i, typicalMin: 3000, typicalMax: 35000, analysis: "Tanker dependency = housing stress — yeh 'water' nahi, recurring invoice hai.", localTip: "Storage + usage schedule — random orders band.", cheaperOption: "Plumbing/leak fix — PKR 1k–5k monthly equivalent relief possible." },
  { id: "utilities-internet", category: "utilities", re: /(internet bill|wifi bill|broadband bill|fiber bill|dsl bill)|(nayatel|stormfiber|ptcl)|((jazz|telenor|zong|ufone).*(home internet|home wifi|fiber|broadband|router|mbps))/i, typicalMin: 1500, typicalMax: 12000, analysis: "Internet mismatch common: speed zyada, usage kam — brand flex expensive.", localTip: "Usage audit → right-size plan — Mbps ka ego choro.", cheaperOption: "Annual promo / downgrade — PKR 300–2k monthly band." },
  // Education
  { id: "edu-school-low", category: "education", re: /(school fee|school fees).*(low|basic)/i, typicalMin: 3000, typicalMax: 12000, analysis: "Low-tier school fee bhi fixed obligation — delay penalty + stress alag line item hai.", localTip: "Due-date reminders + envelope method — boring parent hack gold hai.", cheaperOption: "Annual lump discount agar school de — PKR 1k–5k yearly band realistic." },
  { id: "edu-school-medium", category: "education", re: /(school fee|school fees).*(medium|mid)/i, typicalMin: 12000, typicalMax: 35000, analysis: "Mid school fee family budget ka bada chunk ban sakti hai — books/uniform spikes alag dhamaka.", localTip: "Books/uniform sinking fund alag — 'ek saath sab' shock avoid.", cheaperOption: "Used books + wholesale stationery markets — PKR 2k–8k per term band." },
  { id: "edu-school-high", category: "education", re: /(school fee|school fees|o levels|a levels)/i, typicalMin: 35000, typicalMax: 150000, analysis: "High-tier school = strict cashflow game across full year — surprises allowed nahi.", localTip: "Quarterly education budget review — vibes se zyada numbers.", cheaperOption: "Transport/books optimize — PKR 3k–15k monthly equivalent relief possible." },
  { id: "edu-college", category: "education", re: /(college fee|inter fee|college semester)/i, typicalMin: 6000, typicalMax: 45000, analysis: "College fees manageable jab semester fund pehle se built ho — last week panic expensive.", localTip: "Semester ko monthly sinking fund mein divide — smooth life hack.", cheaperOption: "Second-hand books + digital notes — PKR 2k–8k per semester realistic." },
  { id: "edu-university", category: "education", re: /(university fee|semester fee|tuition fee uni)/i, typicalMin: 25000, typicalMax: 250000, analysis: "Uni fees high-impact — scholarship/aid miss mat karo, ego choro.", localTip: "Installment policy + deadlines pehle verify — admin lines avoid.", cheaperOption: "HEC scholarships + installment planning — PKR 10k–80k immediate relief cases mein." },
  { id: "edu-academy", category: "education", re: /(tuition academy|academy fee|coaching|entry test)/i, typicalMin: 3000, typicalMax: 40000, analysis: "Academy spend ROI-based honi chahiye — trend fee = expensive hobby.", localTip: "Attendance + test scores monthly review — 'paid so must work' rule.", cheaperOption: "YouTube base + selective paid classes — PKR 2k–10k monthly squeeze possible." },
  { id: "edu-books", category: "education", re: /(books|stationery|copies|notebooks)/i, typicalMin: 1000, typicalMax: 20000, analysis: "Books/stationery seasonal spikes — monthly average se plan karo warna term start pain.", localTip: "Term se pehle bulk list ready — panic shop premium.", cheaperOption: "Urdu Bazar / wholesale markets — PKR 1.5k–6k save band." },
  { id: "edu-online-course", category: "education", re: /(online course|udemy|coursera|skill course)/i, typicalMin: 1000, typicalMax: 40000, analysis: "Online course tab worth jab completion + apply ho — tabs open, progress zero = tax.", localTip: "Ek paid course at a time — shiny object syndrome block.", cheaperOption: "Free audit + DigiSkills + YouTube spine — PKR 3k–20k save realistic." },
  { id: "edu-madrassa", category: "education", re: /(madrassa fee|madarsa fee|madrasah fee)/i, typicalMin: 1000, typicalMax: 10000, analysis: "Madrassa fee manageable recurring — small but consistent; track miss mat karo.", localTip: "Books/events alag note — merge blindness avoid.", cheaperOption: "Wholesale stationery + shared transport — PKR 500–2k monthly band." },
  // Health
  { id: "health-medicine", category: "health", re: /(basic medicine|medicine|dawa|pharmacy)/i, typicalMin: 800, typicalMax: 10000, analysis: "Basic dawa recurring ho toh health line item banana chahiye — duplicate packs silent waste.", localTip: "Prescription photo + refill calendar — 'same dawa dobara' trap band.", cheaperOption: "Generic/partner pharmacy options compare — PKR 300–2k monthly realistic." },
  { id: "health-specialist", category: "health", re: /(specialist doctor|consultant|doctor fee)/i, typicalMin: 2000, typicalMax: 20000, analysis: "Specialist zaroori ho sakta hai; delay costly, blind expensive bhi — balance adulting hai.", localTip: "Follow-up optimize — har visit same story expensive.", cheaperOption: "Hospital OPD day slots — PKR 500–3k per visit band possible." },
  { id: "health-lab", category: "health", re: /(lab test|xray|scan|ultrasound|blood test)/i, typicalMin: 1500, typicalMax: 45000, analysis: "Labs high-variance — same test different price reality hai Pakistan mein.", localTip: "Sirf doctor-advised panels — 'full body random' avoid.", cheaperOption: "Accredited labs price check — PKR 1k–8k save realistic." },
  { id: "health-hospital", category: "health", re: /(hospital admission|admission hospital|operation|surgery)/i, typicalMin: 30000, typicalMax: 900000, analysis: "Admission = emergency-heavy — cash buffer + insurance/ panel critical.", localTip: "Har bill document — claim/review ke liye gold.", cheaperOption: "Sehat Sahulat / employer panel — PKR 20k+ out-of-pocket kam cases mein." },
  { id: "health-dental", category: "health", re: /(dental|dentist|root canal|tooth)/i, typicalMin: 2000, typicalMax: 80000, analysis: "Dental delay = bill double — classic regret category.", localTip: "Preventive cleaning schedule — boring save.", cheaperOption: "2–3 clinic quotes — PKR 2k–15k variance common." },
  { id: "health-optical", category: "health", re: /(optical|glasses|specs|lens)/i, typicalMin: 2500, typicalMax: 35000, analysis: "Optical quality-sensitive hai; brand flex hamesha zaroori nahi.", localTip: "Frame reuse + lens update — smart middle path.", cheaperOption: "PriceOye / local optical compare — PKR 1.5k–8k save band." },
  { id: "health-homeopathic", category: "health", re: /(homeopathic|homeopathy)/i, typicalMin: 1000, typicalMax: 12000, analysis: "Homeopathic long-run ho toh monthly cap define karo — open-ended risky.", localTip: "Outcome tracking — feel se zyada facts.", cheaperOption: "Licensed pharmacy generic compare — PKR 300–1.5k band." },
  { id: "health-hakeem", category: "health", re: /(hakeem|dawakhana)/i, typicalMin: 1000, typicalMax: 15000, analysis: "Hakeem spend open-ended na rakho — planned amount calm deta hai.", localTip: "Consult vs dawa cost split note — merge mat karo blind.", cheaperOption: "Treatment plan compare — PKR 500–2k monthly squeeze possible." },
  // Shopping + Entertainment + Family + Work + Housing + Savings
  { id: "shop-clothes", category: "shopping", re: /(clothes regular|clothes|dress|garments)/i, typicalMin: 2000, typicalMax: 30000, analysis: "Regular clothes controllable hai; trend chase = silent inflation — Instagram tax real hai.", localTip: "Quarterly clothing cap lock — 'new drop' anxiety manage karo.", cheaperOption: "Daraz sales + wholesale + off-season — PKR 2k–8k squeeze realistic." },
  { id: "shop-eid", category: "shopping", re: /(eid shopping|eid clothes|eid shoes)/i, typicalMin: 6000, typicalMax: 120000, analysis: "Eid shopping emotional spend — cap ke baghair overshoot almost default mode hai.", localTip: "Per-person envelope budget — family politics kam, numbers zyada.", cheaperOption: "Pre-Ramzan sales windows — PKR 3k–20k save band common." },
  { id: "shop-wedding", category: "shopping", re: /(wedding shopping|bridal shopping|jahez|dowry)/i, typicalMin: 25000, typicalMax: 900000, analysis: "Wedding shopping social pressure driven — financial logic side pe chala jata hai.", localTip: "Must-have vs show-off list alag — drama kam, clarity zyada.", cheaperOption: "Fabric/tailor vs branded readywear — PKR 20k–200k relief cases mein." },
  { id: "shop-electronics", category: "shopping", re: /(electronics|gadget|headphones|smartwatch)/i, typicalMin: 3000, typicalMax: 250000, analysis: "Electronics = specs + warranty matter; impulse = regret SKU.", localTip: "Need-based checklist pehle — dopamine buy baad mein.", cheaperOption: "PriceOye + Daraz official + OLX verified — PKR 2k–30k variance common." },
  { id: "shop-mobile", category: "shopping", re: /(mobile phone|smartphone|iphone|android phone)/i, typicalMin: 20000, typicalMax: 600000, analysis: "Phone large discretionary unless work-critical — EMI total ownership dekhna must.", localTip: "3-year realistic life assume karo — yearly upgrade tax avoid.", cheaperOption: "PTA verified used / open-box — PKR 5k–60k save band." },
  { id: "shop-appliances", category: "shopping", re: /(home appliances|fridge|ac|washing machine|microwave)/i, typicalMin: 15000, typicalMax: 500000, analysis: "Appliance upfront + bill impact dono — energy rating ignore = future pain.", localTip: "Inverter + right size — oversize AC = oversize bill.", cheaperOption: "Seasonal sales + bank installment compare — PKR 5k–50k relief possible." },
  { id: "shop-furniture", category: "shopping", re: /(furniture|sofa|bed|mattress|cupboard)/i, typicalMin: 8000, typicalMax: 400000, analysis: "Furniture quality vary — quick cheap buy often expensive mistake.", localTip: "Material vs labor quote split — transparency first.", cheaperOption: "OLX/Facebook + local carpenter mix — PKR 10k–80k save realistic." },
  { id: "ent-data", category: "entertainment", re: /(mobile data package|data package|bundle|4g package)/i, typicalMin: 800, typicalMax: 7000, analysis: "Data packs chote lagte hain; repeat top-ups stack ho kar leak ban jate hain.", localTip: "Ek monthly bundle + WiFi primary — micro recharges band.", cheaperOption: "Jazz/Telenor right-size bundle — PKR 300–1.5k monthly squeeze." },
  { id: "ent-subscriptions", category: "entertainment", re: /(netflix|youtube premium|spotify|subscription)/i, typicalMin: 800, typicalMax: 12000, analysis: "Subscriptions recurring drain agar usage low — scroll tax.", localTip: "Monthly subscription audit — 2 max rule try karo.", cheaperOption: "Local bundles / family share where legit — PKR 500–3k band." },
  { id: "ent-cinema", category: "entertainment", re: /(cinema|movie ticket)/i, typicalMin: 1500, typicalMax: 15000, analysis: "Cinema occasional fine; habit = popcorn-priced life.", localTip: "Monthly movie count cap — dopamine scheduling.", cheaperOption: "Off-peak + combo control — PKR 500–3k monthly realistic." },
  { id: "ent-sports", category: "entertainment", re: /(cricket|sports|match ticket|sports club)/i, typicalMin: 1000, typicalMax: 30000, analysis: "Sports spend healthy if planned — random gear chase expensive.", localTip: "Group gear share model — solo hero tax kam.", cheaperOption: "Community grounds + second-hand OLX — PKR 1k–7k save band." },
  { id: "ent-gaming", category: "entertainment", re: /(gaming|psn|steam|game pass|in app purchase)/i, typicalMin: 1000, typicalMax: 50000, analysis: "Gaming spend uncontrolled ho toh discretionary bucket explode — microtransactions silent.", localTip: "Monthly gaming wallet cap — hard stop.", cheaperOption: "Sale windows + legal share libraries — PKR 1.5k–10k squeeze possible." },
  { id: "family-child", category: "family", re: /(child expenses|baby|diaper|formula|kids)/i, typicalMin: 5000, typicalMax: 70000, analysis: "Child expenses essential; unplanned aisles shopping = jump scare.", localTip: "Monthly essentials checklist — boring parent meta.", cheaperOption: "Bulk trusted stores — PKR 2k–8k monthly band realistic." },
  { id: "family-parents", category: "family", re: /(parent support|parents support|walidain support)/i, typicalMin: 3000, typicalMax: 100000, analysis: "Parent support valid + honorable — planned transfer calm deta hai.", localTip: "Fixed date transfer — predictability respect dono.", cheaperOption: "Bills direct-pay + medicine planning — PKR 1k–4k leak kam." },
  { id: "family-wedding-contrib", category: "family", re: /(wedding contribution|shaadi contribution)/i, typicalMin: 5000, typicalMax: 300000, analysis: "Family wedding contrib emotional — apni affordability anchor zaroori.", localTip: "Amount pehle decide — last-minute 'aur thora' trap.", cheaperOption: "Cash cap discipline — PKR 5k–50k overshoot avoid realistic." },
  { id: "family-eid-gifts", category: "family", re: /(eid gifts|eidi|gift)/i, typicalMin: 2000, typicalMax: 120000, analysis: "Eid gifts joyful; gifting inflation budget hurt karti hai.", localTip: "Per-household gift cap — love measured in thought, not only PKR.", cheaperOption: "Bundle early buy — PKR 2k–15k save band." },
  { id: "family-qurbani", category: "family", re: /(qurbani|bakra|goat share|cow share)/i, typicalMin: 18000, typicalMax: 250000, analysis: "Qurbani annual obligation — sinking fund na ho toh pressure spike.", localTip: "12-month envelope — boring holy grail.", cheaperOption: "Early booking + share model — PKR 5k–30k relief cases mein." },
  { id: "family-charity", category: "family", re: /(sadqa|charity|donation|zakat)/i, typicalMin: 1000, typicalMax: 120000, analysis: "Charity meaningful — consistency random spikes se better.", localTip: "Dedicated monthly charity line — guilt-free + planned.", cheaperOption: "Planned giving = emergency borrow kam — peace indirect save." },
  { id: "family-helper", category: "family", re: /(domestic helper salary|maid salary|bai salary|driver salary)/i, typicalMin: 8000, typicalMax: 50000, analysis: "Helper fixed household cost — annual raise planning must.", localTip: "Budget mein fixed line — 'adjust ho jayega' myth dangerous.", cheaperOption: "Task optimize overtime/extra helper — PKR 1k–4k monthly squeeze possible." },
  { id: "work-conveyance", category: "work", re: /(office conveyance|office travel|commute office)/i, typicalMin: 3000, typicalMax: 35000, analysis: "Office commute recurring leak unless route strategy clear.", localTip: "Weekly commute cap — vibe commute expensive.", cheaperOption: "Ride-share + bus mix — PKR 1.5k–6k monthly realistic." },
  { id: "work-laptop", category: "work", re: /(laptop|equipment|work setup|office equipment)/i, typicalMin: 10000, typicalMax: 400000, analysis: "Work equipment investment tab jab income link clear ho — flex buy alag cheez.", localTip: "ROI timeline decide — payback story weak ho toh wait.", cheaperOption: "Refurb verified — PKR 10k–70k save band." },
  { id: "work-business", category: "work", re: /(business expense|inventory|shop expense|raw material)/i, typicalMin: 5000, typicalMax: 500000, analysis: "Business vs personal blur = tax + stress double — separation non-negotiable.", localTip: "COGS vs overhead split sheet — boring accountant energy.", cheaperOption: "Wholesale + cash discount — PKR 5k–40k monthly relief possible." },
  { id: "work-freelance-tools", category: "work", re: /(freelancing tools|saas|canva|chatgpt|hosting|domain)/i, typicalMin: 1000, typicalMax: 60000, analysis: "Freelance tools productive; overlap subs = waste stack.", localTip: "Quarterly tool audit — shiny stack kam.", cheaperOption: "Free tiers + annual billing — PKR 1.5k–12k monthly equivalent squeeze." },
  { id: "housing-rent-low", category: "housing", re: /(rent low|low rent|small portion rent)/i, typicalMin: 10000, typicalMax: 30000, analysis: "Low rent manageable; utilities bundle add kar ke real affordability dekho.", localTip: "Rent + utilities combined cap — blind spot yahi.", cheaperOption: "Yearly renewal negotiate — PKR 1k–3k monthly equivalent band." },
  { id: "housing-rent-medium", category: "housing", re: /(rent medium|mid rent|apartment rent)/i, typicalMin: 30000, typicalMax: 80000, analysis: "Mid rent major block — 30–35% income rule anchor useful.", localTip: "Location vs commute tradeoff honest math.", cheaperOption: "One zone shift — PKR 5k–20k monthly relief realistic." },
  { id: "housing-rent-high", category: "housing", re: /(rent high|high rent|dha rent|bahria rent|gulberg rent|rent)/i, typicalMin: 80000, typicalMax: 450000, analysis: "High rent affordability challenge — income strong na ho toh silent crisis.", localTip: "Renewal pe data-based negotiate — ego choro numbers pakro.", cheaperOption: "Downsize / area shift — PKR 15k–80k monthly relief cases mein." },
  { id: "housing-maintenance", category: "housing", re: /(house maintenance|maintenance|society charges)/i, typicalMin: 2000, typicalMax: 35000, analysis: "Maintenance irregular lagta hai; annual average budget chahiye.", localTip: "Monthly sinking fund — emergency repair shock kam.", cheaperOption: "Preventive upkeep — PKR 5k–50k yearly emergency avoid realistic." },
  { id: "housing-plumber-electrician", category: "housing", re: /(plumber|electrician|wiring|pipe repair)/i, typicalMin: 1000, typicalMax: 40000, analysis: "Repair quotes mismatch common — comparison mandatory.", localTip: "Labor vs material split confirm — vague = expensive.", cheaperOption: "2–3 quotes — PKR 1k–8k per job save band." },
  { id: "housing-painting", category: "housing", re: /(painting|paint job|house paint)/i, typicalMin: 5000, typicalMax: 250000, analysis: "Painting one-time heavy — scope creep bill balloon.", localTip: "Phase-wise rooms — cashflow friendly.", cheaperOption: "Off-season contractor booking — PKR 5k–40k save possible." },
  { id: "saving-emergency", category: "savings", re: /(emergency fund|rainy day fund)/i, typicalMin: 1000, typicalMax: 100000, analysis: "Emergency contribution expense nahi — future stress shield hai.", localTip: "Salary day auto-transfer — willpower game mat khelo.", cheaperOption: "Cash leaks cut karke PKR 1k–10k monthly fund shift realistic." },
  { id: "saving-prizebond", category: "savings", re: /(prize bond|prizebond)/i, typicalMin: 100, typicalMax: 40000, analysis: "Prize bond low-risk parking; liquidity + goal alignment check karo.", localTip: "Diversify boring part — stability first.", cheaperOption: "Partial high-liquidity savings — flexibility win." },
  { id: "saving-bank", category: "savings", re: /(bank savings|saving account|rd|fixed deposit)/i, typicalMin: 1000, typicalMax: 300000, analysis: "Bank savings = discipline signal — strong move.", localTip: "Emergency vs goals split accounts — mental accounting useful.", cheaperOption: "Fee-free + better return options — net savings up." },
  { id: "saving-committee", category: "savings", re: /(committee|beesi|bachat committee|committee payment)/i, typicalMin: 1000, typicalMax: 100000, analysis: "Committee social saving — trust + timing risk real; FOMO join expensive.", localTip: "Sirf verified circle — 'cousin ke friend ki committee' red flag energy.", cheaperOption: "Partial bank auto-save shift — default risk kam." },
  // Extra Pakistani scenarios (Roman Urdu + English mix; first regex match wins — keep specific lines before broad ones in this block where needed)
  { id: "pk-mobile-data-topup", category: "utilities", re: /(weekly mb|monthly mb|super card|super duper|internet sim|sim lagao|data sim|mobile internet|4g weekly|4g monthly|whatsapp package|social bundle)/i, typicalMin: 500, typicalMax: 8000, analysis: "Mobile data packages chote lagte hain, lekin har week naya bundle = silent leak — 'sirf PKR 100' wala trap.", localTip: "Ek monthly data plan + WiFi primary; auto-renew SMS har bill date pe check — drama kam.", cheaperOption: "Operator app se loyalty/offers + family group data — realistic PKR 300–2k monthly squeeze." },
  { id: "pk-chai-nashta-outside", category: "food", re: /(chai nashta|office nashta|nashta dhaba|paratha nashta|halwa puri|anda paratha|sada paratha|nihari breakfast|paye nashta)/i, typicalMin: 2000, typicalMax: 18000, analysis: "Chai/nashta daily = chota kharcha story; month end pe total bada — office boys relate karenge silently.", localTip: "3-day office nashta + home flask days — social life thori compromise, wallet zyada happy.", cheaperOption: "Weekly grocery se bulk paratha/anda + office mein chai — PKR 2k–7k monthly band realistic." },
  { id: "pk-rickshaw-meter-ride", category: "transport", re: /(rickshaw fare|riksha fare|auto rickshaw|meter cab|careem bike|indrive bike|short mile rikshaw)/i, typicalMin: 3000, typicalMax: 20000, analysis: "Rickshaw per-ride spend stack hota hai — especially short hops jahan patience zero.", localTip: "Fixed office route monthly deal + peak avoid; 'bas corner tak' 10 times = full trip cost.", cheaperOption: "Same route pe bus/chingchi alternate days — PKR 2k–8k monthly squeeze possible." },
  { id: "pk-chingchi-daily-commute", category: "transport", re: /(chingchi daily|qingqi daily|gali chingchi|route van|suzuki pickup fare)/i, typicalMin: 2500, typicalMax: 12000, analysis: "Chingchi daily commute cheap feel deti hai, lekin do routes + rain surge = bill up.", localTip: "Monthly pass style deal same driver se — cashflow predictable.", cheaperOption: "Cycle/walk last-mile short — PKR 500–2k monthly micro save bhi count hota hai." },
  { id: "pk-school-fees-generic", category: "education", re: /(monthly school|school tuition|school dues|admission fee school|security fee school|annual charges school|prospectus fee)/i, typicalMin: 5000, typicalMax: 80000, analysis: "School fees fixed pressure — late fee + 'activity charges' quietly add up.", localTip: "Calendar reminders + separate kids education envelope — surprises kam.", cheaperOption: "Sibling discount / early payment discount poochho — PKR 2k–15k yearly relief realistic." },
  { id: "pk-madrassa-donation-extra", category: "education", re: /(madrassa donation|madarsa chanda|masjid fee monthly|imam support|qari sahab fee|hifz class fee|deeniyat fee)/i, typicalMin: 500, typicalMax: 15000, analysis: "Madrassa/masjid side contributions noble hain, lekin open-ended ho toh monthly leak ban jati hai.", localTip: "Fixed monthly cap + receipt habit — transparency calm deti hai.", cheaperOption: "Essentials bulk donate (dates/ration) vs cash random — PKR 500–3k planning win." },
  { id: "pk-wapda-fuel-surcharge", category: "utilities", re: /(fuel adjustment|fca charges|electricity surcharge|bijli recovery|consumer bill adjustment|truel|iesco bill|lesco bill|fesco bill|mepco bill)/i, typicalMin: 2000, typicalMax: 60000, analysis: "WAPDA bill ke fuel adjustment / surcharges alag shock line item — usage same, bill up.", localTip: "Units track karo + heavy appliances stagger — boring but bill pe asar.", cheaperOption: "LED + geyser timer + AC discipline — PKR 1k–6k monthly squeeze cases mein." },
  { id: "pk-sngpl-meter-rent", category: "utilities", re: /(sngpl meter|gas meter rent|gas infrastructure|gas surcharge|domestic gas slab)/i, typicalMin: 2000, typicalMax: 25000, analysis: "SNGPL domestic gas — slab + meter charges mila ke winter mein drama hota hai.", localTip: "Leak check + burner clean + cooking batching — small fixes stack.", cheaperOption: "Solar water heater long-term consider — payback slow but gas load kam." },
  { id: "pk-medical-store-counter", category: "health", re: /(medical store|dispensary|counter syrup|tonic|vitamin tablets|painkiller monthly|pharmacy bill)/i, typicalMin: 500, typicalMax: 12000, analysis: "Medical store counter items recurring — brand swap quietly saves without drama.", localTip: "Same salt name doctor se likhwa ke generic compare — ego nahi, science + budget.", cheaperOption: "Wholesale strip + 90-day refill planning — PKR 500–3k monthly realistic." },
  { id: "pk-eid-shopping-bazaar", category: "shopping", re: /(chand raat|eid bazaar|mehndi bazaar|eid shoes kids|eid clothes kids|bacha eid shopping)/i, typicalMin: 4000, typicalMax: 150000, analysis: "Chand raat / bazaar energy = impulse max — bache + lawn + shoes sab ek breath mein.", localTip: "List + cash envelope — card tap = regret speedrun.", cheaperOption: "Wholesale bazaar morning slots + bundle bargaining — PKR 3k–25k save cases mein." },
  { id: "pk-qurbani-logistics", category: "family", re: /(qurbani transport|bakra transport|animal pickup|mandi fee|qurbani skin|qasai tip|butcher eid)/i, typicalMin: 2000, typicalMax: 35000, analysis: "Qurbani ke logistics costs alag line item — mandi, transport, tips quietly stack.", localTip: "Group logistics plan pehle — solo hero tax avoid.", cheaperOption: "Local cooperative pool + early slot — PKR 2k–12k squeeze realistic." },
  { id: "pk-committee-rotating", category: "savings", re: /(rotating savings|rosca|street committee|gali committee|office committee|monthly pool|committee installment|beesi payout)/i, typicalMin: 2000, typicalMax: 120000, analysis: "Committee/bachat pool social finance hai — payout timing risk + FOMO contribution dono real.", localTip: "Liquid emergency fund pehle; committee secondary — hierarchy clear rakho.", cheaperOption: "Smaller ticket verified circle — big FOMO pool se monthly PKR 2k–10k stress kam ho sakta hai." },
  { id: "pk-helper-ration-eidi", category: "family", re: /(maid ration|driver ration|domestic helper food|bai eidi|driver bonus|staff bonus eid)/i, typicalMin: 3000, typicalMax: 40000, analysis: "Helper ration / Eid bonus valid cultural line items — unplanned = budget puncture.", localTip: "Annual calendar banao: Eid + increment + medical — surprises kam.", cheaperOption: "Bulk ration monthly contract style — PKR 1k–5k volatility kam realistic." },
  { id: "pk-bike-petrol-daily-commute", category: "transport", re: /(daily bike petrol|bike commute fuel|motorcycle daily fuel|office bike fuel)/i, typicalMin: 4000, typicalMax: 22000, analysis: "Bike petrol daily commute = burn rate high — short trips engine cold = worse average.", localTip: "Trip chain + tyre pressure + service on time — 'petrol mehnga' + bad habits double hit.", cheaperOption: "Fuel card promos + carpool alternate days — PKR 1.5k–6k monthly squeeze possible." },
  { id: "pk-generator-diesel", category: "utilities", re: /(generator diesel|genset diesel|diesel can generator|generator runtime diesel)/i, typicalMin: 5000, typicalMax: 60000, analysis: "Generator diesel runtime expensive — especially big genset + poor load management.", localTip: "Selective circuits backup; poora mohalla backup apni salary pe nahi.", cheaperOption: "Inverter lithium long-term compare + solar quote 2–3 — monthly PKR 3k–15k fuel pain kam ho sakta hai post setup." },
  { id: "pk-nan-katauti-recharge", category: "utilities", re: /(easyload|easy paisa load|jazz load|telenor load|zong load|ufone load|scratch card mobile)/i, typicalMin: 300, typicalMax: 15000, analysis: "Easyload / scratch card rhythm choti lagti hai, lekin har roz top-up = monthly phone tax.", localTip: "Bank app bundle + monthly plan — micro loads band.", cheaperOption: "Postpaid/bundle if usage stable — PKR 500–4k monthly realistic save band." },
  { id: "pk-tuition-academy-monthly", category: "education", re: /(home tuition|home tutor|class [1-9] tuition|matric tuition|fsc tuition|o level tuition|a level tuition)/i, typicalMin: 4000, typicalMax: 50000, analysis: "Home tuition monthly stack ho toh school fee ke saath double engine ban jata hai.", localTip: "Weak subjects only rule — full syllabus hero mode expensive.", cheaperOption: "Group tuition / study circle hybrid — PKR 3k–12k monthly squeeze realistic." },
  { id: "pk-water-cooler-dispenser", category: "utilities", re: /(water dispenser|water cooler|20 liter|20l water|nestle water|refill jar)/i, typicalMin: 2000, typicalMax: 15000, analysis: "Jar/dispenser water recurring — health peace + cost tradeoff clear rakho.", localTip: "RO maintenance schedule — random jar panic kam.", cheaperOption: "RO + UV service contract compare — PKR 1k–4k monthly jar spend kam ho sakta hai." },
  { id: "pk-parking-toll-city", category: "transport", re: /(parking fee|mall parking|toll plaza|m tag|city toll|clifton parking)/i, typicalMin: 1000, typicalMax: 12000, analysis: "Parking + tolls chote line items; daily office = silent stack.", localTip: "Monthly parking pass where available — per trip premium avoid.", cheaperOption: "Bike last mile + car park edge — PKR 1k–5k monthly squeeze possible." },
  { id: "pk-bank-charges-sms", category: "savings", re: /(bank charges|sms alert charges|annual fee card|ledger fee|account maintenance)/i, typicalMin: 200, typicalMax: 8000, analysis: "Bank charges / SMS alerts boring leak — ignore mat karo, yeh creep category hai.", localTip: "SMS package off where app enough — small cuts stack.", cheaperOption: "Low-fee digital bank compare — PKR 200–2k monthly realistic relief." },
];

export const findOfflineScenario = (expenseName: string, category: string): ExpenseScenario | null => {
  const text = `${expenseName} ${category}`.toLowerCase();
  for (const scenario of OFFLINE_EXPENSE_SCENARIOS) {
    if (scenario.re.test(text)) {
      return scenario;
    }
  }
  return null;
};

